#!/bin/bash -eux
# --- Start MAAS 1.0 script metadata ---
# name: do-gpu-burn
# title: do-gpu-burn
# description: do-gpu-burn
# script_type: test
# hardware_type: gpu
# timeout: 00:10:00
# --- End MAAS 1.0 script metadata ---
set -o pipefail
shopt -s inherit_errexit

sudo apt-get install build-essential -y

# https://docs.nvidia.com/datacenter/tesla/tesla-installation-notes/index.html#runfile
sudo rmmod nouveau || true
sudo sh ./$(basename $(curl -s -w "%{url_effective}" https://us.download.nvidia.com/tesla/535.104.12/NVIDIA-Linux-x86_64-535.104.12.run -O)) -s

# https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
  && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list \
  && \
    sudo apt-get update

apt-get install docker.io nvidia-container-runtime -y

nvidia-ctk runtime configure

git clone https://github.com/wilicc/gpu-burn
cd gpu-burn && make image
docker run --gpus all gpu-burn
# docker run --gpus all gpu-burn nvidia-smi
